### ISSUE TITLE
Service chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by mollinaca** [mollinaca/chromedriver-test#1]
```
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    driver = webdriver.Chrome(options=options)
  File "/home/sho/.local/share/virtualenvs/flyers-OhApUgB6/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/sho/.local/share/virtualenvs/flyers-OhApUgB6/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/sho/.local/share/virtualenvs/flyers-OhApUgB6/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127
```

**Comment by mollinaca** [comment]
```
(chromedriver-test) sho@chromebook1:~/workspace/chromedriver-test$ pip list | grep chrome
chromedriver-binary 91.0.4472.101.0

(chromedriver-test) sho@chromebook1:~/workspace/chromedriver-test$ snap list | grep chromium
chromium           91.0.4472.114               1646   latest/stable  canonical*  -

(chromedriver-test) sho@chromebook1:~/workspace/chromedriver-test$ which chromederiver
```
chromederiver はどこ？

**Comment by mollinaca** [comment]
```
(chromedriver-test) sho@chromebook1:~/workspace/chromedriver-test$ chromedriver-path
/home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/chromedriver_binary

(chromedriver-test) sho@chromebook1:~/workspace/chromedriver-test$ /home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/chromedriver_binary/chromedriver
/home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/chromedriver_binary/chromedriver: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**Comment by mollinaca** [comment]
```
(chromedriver-test) sho@chromebook1:~/workspace/chromedriver-test$ ./test.py
Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    driver = webdriver.Chrome(options=options)
  File "/home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
```

オプションで
```
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
```
を指定してるが上記エラー

**Comment by mollinaca** [comment]
```
(chromedriver-test) sho@chromebook1:~/workspace/chromedriver-test$ /home/sho/.local/share/virtualenvs/chromedriver-test-LAl7e4Da/lib/python3.8/site-packages/chromedriver_binary/chromedriver
Starting ChromeDriver 91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```
chromedriver 自体は起動する
